name = "Ballspack 3: Interdimensional Roadtrip"
author = "enjarai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "492b084bd0f05b78ad7a794150268478a35aa83e7d6f7be1c4bec3cac404c8a9"

[versions]
fabric = "0.15.1"
minecraft = "1.20.1"
