name = "Ballspack 3: Interdimensional Roadtrip"
author = "enjarai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1c625683e7943ab9cd51599cae6ed778445c6bd651de6005b00a78a04feae59"

[versions]
fabric = "0.15.1"
minecraft = "1.20.1"
