name = "Ballspack 3: Interdimensional Roadtrip"
author = "enjarai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae6f710ea0089cd183f58aef99fd8728113a2c555327bfaa3944d07724712936"

[versions]
fabric = "0.15.1"
minecraft = "1.20.1"
