name = "Ballspack 3: Interdimensional Roadtrip"
author = "enjarai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "174b2ee3ab04bf15199779c38d9d2391fa236bef7eb6ffe3cd1dae18207e9343"

[versions]
fabric = "0.15.1"
minecraft = "1.20.1"
