name = "Ballspack 3: Interdimensional Roadtrip"
author = "enjarai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b41d34455651be1aa3ceb7b8c8cbf54308b5a8bd7eb1895aa043ea957d58f77"

[versions]
fabric = "0.15.1"
minecraft = "1.20.1"
