name = "Ballspack 3: Interdimensional Roadtrip"
author = "enjarai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "875a4680ec16a582e0629ec3b2cc66fa339e1300b8d383d87ffbf3c6621b08ff"

[versions]
fabric = "0.15.1"
minecraft = "1.20.1"
