name = "Ballspack 3: Interdimensional Roadtrip"
author = "enjarai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c470dd11cff56c6c040f8c36174e5837a9bf67ea8614f1acf5f849a6cb3f2c3"

[versions]
fabric = "0.15.1"
minecraft = "1.20.1"
