name = "Ballspack 3: Interdimensional Roadtrip"
author = "enjarai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed965c69deaec155f107c52d3ac6a6d4de4a5ac9b7880e3bd09a3b58bc2b640d"

[versions]
fabric = "0.15.1"
minecraft = "1.20.1"
