name = "Ballspack 3: Interdimensional Roadtrip"
author = "enjarai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31d1b66d0f4588158dc7b74f1bda49b9949666927d52996aff9b24bf11f58dae"

[versions]
fabric = "0.15.1"
minecraft = "1.20.1"
