name = "Ballspack 3: Interdimensional Roadtrip"
author = "enjarai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe16308dabe36d3bffde798bf353726f627f4fd862323040fedca3823a17264c"

[versions]
fabric = "0.15.1"
minecraft = "1.20.1"
