name = "Ballspack 3: Interdimensional Roadtrip"
author = "enjarai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1de9dedc985b0190fb785f69edf661bf8ca58b96ccb11df5b48ec1d8a44e096d"

[versions]
fabric = "0.15.1"
minecraft = "1.20.1"
