name = "Ballspack 3: Interdimensional Roadtrip"
author = "enjarai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4be47006cf2307da7a157b08c290b7545a7a468c4af78a1366457c560c7fb23"

[versions]
fabric = "0.15.1"
minecraft = "1.20.1"
