name = "Ballspack 3: Interdimensional Roadtrip"
author = "enjarai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3aabaf139ed418b07e4c284cb1c816dec4638f8590442f5783dd0570bbb2447a"

[versions]
fabric = "0.15.1"
minecraft = "1.20.1"
