name = "Ballspack 3: Interdimensional Roadtrip"
author = "enjarai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db118ef6f58cc030b7182b86943720f25396991c17911cc57fda33cef9e846c2"

[versions]
fabric = "0.15.1"
minecraft = "1.20.1"
