name = "Ballspack 3: Interdimensional Roadtrip"
author = "enjarai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "060a79ef1dcb8896d0404d32a81da2abf58505db64badbb8a07479834a6c1ade"

[versions]
fabric = "0.15.1"
minecraft = "1.20.1"
